version: "3.7"
services:
  app:
    build: .
    image: docker.pkg.github.com/ahushh/failchan-api/failchan-api_app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
