version: "3.7"
services:
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: develop
    volumes:
      - postgres
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis  
  adminer:
    image: adminer
    depends_on: postgres
    ports:
      - 8081:8080

volumes:
  redis:
  postgres: